"""Initial structure

Revision ID: 01
Revises:
Create Date: 2022-06-01 05:24:47.005058

"""
import fastapi_users_db_sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "01"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", fastapi_users_db_sqlalchemy.guid.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_email"), ["email"], unique=True)

    op.create_table(
        "donation",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", fastapi_users_db_sqlalchemy.guid.GUID(), nullable=True),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("full_amount", sa.Integer(), nullable=True),
        sa.Column("invested_amount", sa.Integer(), nullable=True),
        sa.Column("fully_invested", sa.Boolean(), nullable=False),
        sa.Column("create_date", sa.DateTime(), nullable=False),
        sa.Column("close_date", sa.DateTime(), nullable=True),
        sa.CheckConstraint("full_amount >= 0", name="check_full_amount_positive"),
        sa.CheckConstraint(
            "invested_amount >= 0", name="check_invested_amount_positive"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("charityproject", schema=None) as batch_op:
        batch_op.alter_column(
            "invested_amount", existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("charityproject", schema=None) as batch_op:
        batch_op.alter_column(
            "invested_amount", existing_type=sa.INTEGER(), nullable=False
        )

    op.drop_table("donation")
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_email"))

    op.drop_table("user")
    # ### end Alembic commands ###
